### ISSUE TITLE
Support for a folder id inside a repository

### ISSUE THREAD

**Issue by vishalkwatra** [cap-js/sdm#65]
Hi Team,

Is there any support for this plugin to make use of folder id inside a repository id for e.g. rep=guid1&obj=guid2 where obj is a folder?

Regards,
Vishal Kwatra

**Comment by yashmeet29** [comment]
Hi @vishalkwatra,
No, the plugin doesn't supports the use of folder id inside a respository id.

**Comment by yashmeet29** [comment]
@vishalkwatra could you explain about your use-case where you need support of folder id?
