### ISSUE TITLE
My app crashes when trying to save without having added at least one attachment

### ISSUE THREAD

**Issue by waldpark** [cap-js/sdm#73]
The function

async attachDeletionData(req)

in Line 207 inside

https://github.com/cap-js/sdm/blob/develop/lib/sdm.js

expects

diffData.attachments (in Line 214)

to be existing which is not the case when you have no attachments. 
In such a case you cannot save the referencing entity.

Please add a check for existence of diffData.attachments before using diffData.attachments.filter().

Best regards
Adrian

**Comment by yashmeet29** [comment]
Hi @waldpark,
could you please share the steps to reproduce the issue?

Regards,
Yashmeet

**Comment by yashmeet29** [comment]
Hi @waldpark, Can you please share the steps to reproduce this issue?

**Comment by waldpark** [comment]
Hi Yashmeet,

it is simple. Just create a simple CAP App like written in the instructions of
https://github.com/cap-js/sdm

Deploy the app to BTP. Run the UI. Switch to Edit Mode.
DO NOT add any attachments. Edit some other fields. Press Save. This should run into the above mentioned error.

Best regards,
Adrian

**Comment by rishikunnath2747** [comment]
Hi @waldpark, we’ve been able to reproduce the issue and are actively working on a fix. Thank you for bringing this bug to our attention.

**Comment by rishikunnath2747** [comment]
Hi @waldpark, this bug has been resolved in [v1.2.2](https://github.com/cap-js/sdm/blob/develop/CHANGELOG.md#version-122) which is now available on [npm](https://www.npmjs.com/package/@cap-js/sdm/v/1.2.2).
