### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'uaa')

### ISSUE THREAD

**Issue by AelElliotBanyard** [cap-js/sdm#75]
I'm encountering an issue with the capjs/sdm package while saving a draft in development mode. 

The following error is thrown:
Cannot read properties of undefined (reading 'uaa')

Steps to Reproduce:

Start the application on local device.
Try to save a draft.
Error pops up on screen.
Expected Behavior: The draft should save successfully without errors.

Actual Behavior: The error Cannot read properties of undefined (reading 'uaa') is thrown, preventing the draft from being saved.

Environment:

capjs/sdm version: 1.2.0
Development mode
Node.js version: ^18
Other relevant dependencies or configurations: @sap/cds-dk: 7.9.2
Additional Information: This error only appears to happen in development mode.
I'm happy to provide further information if needed to help troubleshoot the issue.

**Comment by rashmiangadi11** [comment]
Hi[AelElliotBanyard](https://github.com/AelElliotBanyard),
I think you are running this application locally, if it is so than you need to configure approuter which can generate the JWT token and use it for token exchange.
Kindly refer this blog to set up approuter and run your application locally

https://community.sap.com/t5/technology-blogs-by-members/test-your-cap-nodejs-applications-with-authentication-locally/ba-p/13417243

Regards,
Rashmi

**Comment by AelElliotBanyard** [comment]
Hi @rashmiangadi11,
Thank you for your reccomendation. The implementation of the approuter did not fix the issue. 
Kind Regards
Ael

**Comment by rashmiangadi11** [comment]
Can we have  a call tomorrow. Could u please schedule a meeting

**Comment by AelElliotBanyard** [comment]
Do you mean me?

**Comment by rashmiangadi11** [comment]
Yes otherwise could you please send your email address and preferred time slot to schedule a meeting

**Comment by AelElliotBanyard** [comment]
You can contact me at ael.banyard@wavestone.eu . I am available from 10 am until 12 pm and from 1 pm until 4 pm GMT+2. Kind Regards

**Comment by rashmiangadi11** [comment]
Could you please tell me the timezone of yours to schedule a meeting.

**Comment by ashishjain14** [comment]
Hi @AelElliotBanyard : Ideal setup would be to deploy your application on BTP and then run it against a provisioned Document Management Integration option instance. Have you tried testing the application using the step as suggested in the [README](https://github.com/cap-js/sdm?tab=readme-ov-file#deploying-and-testing-the-application)?

**Comment by AelElliotBanyard** [comment]
Hi @ashishjain14 yes. the application is deployed to BTP and works fine there but the problem is I cannot test implemented features locally and this makes the development process very long.

**Comment by AelElliotBanyard** [comment]
@rashmiangadi11 Timezone is in the comment but I am in CEST.

**Comment by ashishjain14** [comment]
@AelElliotBanyard : Can you share more details on the issue you are facing with your local development?

**Comment by AelElliotBanyard** [comment]
@ashishjain14: I have an Entity which is using attachments. This Entity has odata draft enabled. When creating an Object and hitting save i get the error message mentioned in the title of issue. Because of the BTP that we are using we have implemented the fix with the versioned repository.

**Comment by AelElliotBanyard** [comment]
@ashishjain14 Any Updates?

**Comment by ashishjain14** [comment]
> @ashishjain14: I have an Entity which is using attachments. This Entity has odata draft enabled. When creating an Object and hitting save i get the error message mentioned in the title of issue. Because of the BTP that we are using we have implemented the fix with the versioned repository.

So If I understand correctly you are using a custom version of library where you have added a custom fix to support versioned repo?

**Comment by AelElliotBanyard** [comment]
> > @ashishjain14: I have an Entity which is using attachments. This Entity has odata draft enabled. When creating an Object and hitting save i get the error message mentioned in the title of issue. Because of the BTP that we are using we have implemented the fix with the versioned repository.
> 
> So If I understand correctly you are using a custom version of library where you have added a custom fix to support versioned repo?

no using the normal version with npm install ... and yes this is the fix: 
```js
 const sdmUtils = require("@cap-js/sdm/lib/util/index");

  // Override the isRepositoryVersioned function directly in the utility module
  sdmUtils.isRepositoryVersioned = function (...args) {
    console.error("override isRepositoryVersioned");
    return false;
  };
```

**Comment by ashishjain14** [comment]
Do you still the same error with non-versioned repository and using the released version of our library?

**Comment by AelElliotBanyard** [comment]
no the fix works

**Comment by ashishjain14** [comment]
Hi @AelElliotBanyard  : We are little lost into what is the actual problem here. Your initial point was local testing not working and now I see you have another problem where you are trying to override versioned repo check and running a deployment. Can you let us know what is the problem you are facing?

**Comment by AelElliotBanyard** [comment]
there is no problem with the repo that works fine that is from issue #67 my boss comented on in this repo (@korayyersel). That is not the problem! the problem is with local development

**Comment by ashishjain14** [comment]
Can you try this blog to run the app locally(https://community.sap.com/t5/technology-blogs-by-sap/run-node-js-applications-with-authentication-locally-sap-btp-security/ba-p/13540122) . In case this does not work I suggest you to create a service now ticket.

**Comment by AelElliotBanyard** [comment]
I implemented the approuter but the local app still wants me to sign in this way:
![image](https://github.com/user-attachments/assets/1da5464c-8bff-4de7-b974-7d1bdd6e1f3d)
