### ISSUE TITLE
Getting 500 internal server error

### ISSUE THREAD

**Issue by AdilBashaSAP** [cap-js/sdm#80]
Hi Team,
Created 2 subaccounts: 1. Dev, 2. Test
1. Dev: BAS, DMS, etc
2. Test: Only SHC instance

In Dev subacc, I'm trying to create a demo CAP app to upload the attachments.
So, I've followed the steps given in this repo.
- Cloned the incidents app
- added the node modules: sdm and all
- db/attachments.cds 
- repoID (non-versioned repo) in package.json
![image](https://github.com/user-attachments/assets/671921f3-fdbd-4cf7-9570-3acf93ed42fb)
- updated mta yaml
- Deployed the app successfully to BTP
- When I open the app from BTP, app is opening and working well in the DRAFT
- But I try to save it, its giving 'Internal Server Error'.
![image](https://github.com/user-attachments/assets/ff31ceb2-fc5f-43d1-bd97-68766d91b838)

Kindly help me to resolve the issue. I'm from Hyd, India. 
Thanks & Regards, Adil Basha.

**Comment by ashishjain14** [comment]
Hi @AdilBashaSAP : Can you share the zip of your app?

**Comment by AdilBashaSAP** [comment]
Hi Ashish, Thanks for responding to the issue.
Getting internal server issue due to, I've given 'sdm-di-instance' in the mta.yaml, but later came to know that, I should give the SAP DMS, integration Instance name. Its working after changing that.

Could you please tell me, how can upload multiple files at once using this plugin?
I'm unable to upload multiple files at once. 
If not possible, any work arounds? or whether this feature will be added in future?

Thanks & Regards, Adil Basha.

**Comment by ashishjain14** [comment]
Do you mean the following?

1. Select Upload
2. In File Browser window->Select multiple files
3. Click Open

**Comment by AdilBashaSAP** [comment]
Yes, you are right.
In the File browser window, I'm able to select only 1 file at a time to upload.

**Comment by ashishjain14** [comment]
Ok currently that is the expected behaviour. We may consider multi-select capability in the future. For now I am closing this issue.

**Comment by AdilBashaSAP** [comment]
It would be good if you can add it under 'Restrictions' section.
